### ISSUE TITLE
Update to last version

### ISSUE THREAD

**Issue by seravifer** [angular-extensions/svg-icons-builder#26]
Hi.
The last version of the svg-to-ts is 6.0.1.
It would be great to update to this latest version.

**Comment by seravifer** [comment]
@kreuzerk I can work on this if you don't have time.

**Comment by nivekcode** [comment]
@seravifer that would be epic since I am currently pretty busy.

**Comment by seravifer** [comment]
Done #27 😄

**Comment by nivekcode** [comment]
@seravifer thx a lot for this PR. I saw that you committed these changes as chore which is perfectly fine. However, currently, the repository is set up to not release new versions on npm on chore commits.

Let me know in case you need this fix to be released.

**Comment by nivekcode** [comment]
Again thx for the great work 👏

**Comment by seravifer** [comment]
Oh, I didn't know that.

Yes, I need to be released to use on my repo.

@kreuzerk What can we do to launch a new version?

**Comment by nivekcode** [comment]
We have to commit it accordingly. The way I understood the branch we merged actually is a breaking change. I will try to find some time today to release the new version. (v2.0.0)

**Comment by nivekcode** [comment]
Hi @seravifer I just released v2. Its now available on npm. Thx a lot for the collaboration 👍
