### ISSUE TITLE
Extend schema.json

### ISSUE THREAD

**Issue by nivekcode** [angular-extensions/svg-icons-builder#9]
Adjust `schema.json` to contain options for all `conversionTypes` (`constants`, `objects`, `files`).

**Comment by nivekcode** [comment]
I am not yet sure if we should add one builder that then internally differentiates between the 3 `conversionTypes` or if we should add three builders. One for `constants`, one for `objects` and one for `files`. Having three builders would have the advantage that we do not mix the options and each builder would have a clear `schema.json`. 

@kaltepeter Thoughts?

**Comment by kaltepeter** [comment]
@kreuzerk I debated that a bunch in my head too. I agree that three has a cleaner schema, we could always start separate unless it really doesn't make sense. I imagine any shared bits could be abstracted out easy on code side, maybe schema as well.

I think I lean towards 3 unless it's unruly when we get into it.
